### ISSUE TITLE
Fixing the API issue with Selinium webdriver

### ISSUE THREAD

**Issue by johnnydhnguyen** [KevinTrinh1227/Prize-Pick-Predications#4]
I've found a crude workaround the limiting of the prizepicks API.  My solution uses a chromium webdriver to access the end point via a browser and scrapes the data using beautiful soup.

###########################################
# requirements: download the version of selenium webdriver that matches with your google
# chrome and paste it into your CWD.
# link: https://chromedriver.chromium.org/downloads
###########################################

from selenium import webdriver
from bs4 import BeautifulSoup
import json

driver = webdriver.Chrome()

#Initializes a web driver and opens the page in a new chrome window
url = 'https://api.prizepicks.com/projections?league_id=7'
driver.get(url)

#Beautiful soup parsing through the page contents
content = driver.page_source
soup = BeautifulSoup(content, 'html.parser')
pre_tag = soup.find('pre') #finds the tag starting with "pre"

#Dumps the json contents into the filenamed "pre_formatted_predictions.json"
json_text = pre_tag.text
data = json.loads(json_text)
filename = "pre_formatted_predictions.json"
with open(filename, "w") as outfile:
    json.dump(data, outfile, indent = 1)

**Comment by KevinTrinh1227** [comment]
I have now just implemented the selenium driver method in the project. I also had also gotten a similar suggestion from Dawson Diharce from TTU. Thank you for the idea!
